"""Provision a local SearXNG instance for web_search.

Why this module exists: the upstream image ships with JSON output DISABLED and
the bot limiter ENABLED, so a bare `docker run searxng/searxng` produces an
instance the agent cannot query — it returns HTML and eventually HTTP 429. This
writes the one settings file that makes the JSON API usable, then starts the
container.

SECURITY: the container is published to 127.0.0.1 only. SearXNG's JSON API has
no authentication, so binding it to 0.0.0.0 would put an open search proxy on
the local network. The generated settings.yml also gets a random secret_key
(the upstream template ships a well-known placeholder) and 0600 permissions.

Docker is optional throughout. Every entry point degrades to a clear message
rather than an exception when it is absent — the bundled keyless ddgs backend
covers machines without it.
"""
from __future__ import annotations

import json
import re
import secrets
import shutil
import subprocess
import time
import urllib.request
from pathlib import Path

CONTAINER_NAME = "agent8088-searxng"
IMAGE = "searxng/searxng:latest"
# Override with `searxng_host_port` in config.txt when 8888 is already taken.
# The HOST is deliberately not configurable — see the SECURITY note above: this
# container must never be published beyond loopback.
DEFAULT_HOST_PORT = 8888


def base_url(port: int | None = None) -> str:
    """Loopback JSON-API endpoint for the provisioned container."""
    return f"http://127.0.0.1:{port or DEFAULT_HOST_PORT}/search?q="


# Retained for callers that imported the constants directly.
HOST_PORT = DEFAULT_HOST_PORT
BASE_URL = base_url()

_SETTINGS_TEMPLATE = """# Generated by agent8088 — safe to edit.
use_default_settings: true
server:
  secret_key: "{secret}"
  # Off so the local JSON API is reachable. Safe here only because the
  # container is published to loopback; do not expose this instance.
  limiter: false
  image_proxy: true
search:
  # `json` is NOT enabled upstream by default — without it the agent receives
  # HTML and every search fails with a parse error.
  formats:
    - html
    - json
"""


def settings_dir(home: Path) -> Path:
    return Path(home) / "searxng"


def write_settings(home: Path) -> Path:
    """Create (or reuse) settings.yml under *home*.

    Idempotent: an existing file's secret_key is preserved so a restart does
    not invalidate sessions or rewrite a file the user may have customised.
    """
    directory = settings_dir(home)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "settings.yml"
    # encoding is explicit, and a file that is not UTF-8 is regenerated rather
    # than kept. An older build wrote this template through the locale codepage,
    # so on Windows the em-dash in line 1 landed as a lone 0x97; SearXNG reads
    # settings.yml as UTF-8 and crash-looped on it. Bare read_text() decoded
    # that same file happily as cp1252, matched the secret_key, and returned
    # early — so setup preserved the corruption instead of repairing it.
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            existing = ""
        if re.search(r'secret_key:\s*"([^"]+)"', existing):
            return path
    # Written through the engine's private-file helper rather than chmod(0o600):
    # this file holds a secret_key, and on Windows chmod cannot express
    # owner-only — the file would keep its inherited SYSTEM/Administrators ACL
    # while still reading as "0600" to a POSIX-shaped check.
    from .engine import _write_private_text

    _write_private_text(path, _SETTINGS_TEMPLATE.format(secret=secrets.token_hex(32)))
    return path


def _docker():
    return shutil.which("docker")


def _run(argv, timeout=90):
    # check=False: callers inspect returncode and surface docker's own message.
    return subprocess.run(argv, capture_output=True, text=True,
                          timeout=timeout, check=False)


def status() -> dict:
    """Whether the managed container exists and is running."""
    docker = _docker()
    if not docker:
        return {"running": False, "detail": "docker is not installed"}
    try:
        # Restarting is reported alongside Running because docker sets
        # State.Running=true for a container in a crash loop. Trusting Running
        # alone made `start()` answer "already running" for a container that had
        # never once served a request, so setup skipped the restart that would
        # have picked up a repaired settings.yml and only the readiness probe
        # noticed — leaving the instance permanently broken across re-runs.
        result = _run([docker, "inspect", "-f",
                       "{{.State.Running}} {{.State.Restarting}}",
                       CONTAINER_NAME], timeout=15)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"running": False, "detail": str(exc)}
    if result.returncode != 0:
        return {"running": False, "detail": "container does not exist"}
    fields = (result.stdout or "").split()
    running = bool(fields) and fields[0] == "true"
    restarting = len(fields) > 1 and fields[1] == "true"
    if restarting:
        return {"running": False, "restarting": True,
                "detail": "container is restarting — check `docker logs "
                          f"{CONTAINER_NAME}`"}
    return {"running": running, "restarting": False,
            "detail": "running" if running else "container exists but is stopped"}


def start(home: Path, port: int | None = None) -> dict:
    """Write settings, then start (or restart) the container on loopback."""
    port = port or DEFAULT_HOST_PORT
    docker = _docker()
    if not docker:
        return {"ok": False,
                "detail": "docker is not installed — the bundled keyless ddgs "
                          "fallback is already handling web_search, or point "
                          "search_base_url at a remote instance"}
    settings = write_settings(home)
    existing = status()
    if existing.get("running"):
        return {"ok": True, "detail": "already running",
                "base_url": base_url(port)}
    # Remove any leftover so `docker run` does not fail on a name clash. A
    # crash-looping container counts: matching only the stopped wording left a
    # restarting one in place, and the name clash then masked the real fault.
    if existing.get("restarting") or existing.get("detail") == (
            "container exists but is stopped"):
        try:
            _run([docker, "rm", "-f", CONTAINER_NAME], timeout=30)
        except (OSError, subprocess.TimeoutExpired):
            pass
    argv = [
        docker, "run", "-d", "--name", CONTAINER_NAME,
        "--restart", "unless-stopped",
        # Loopback ONLY: the JSON API is unauthenticated.
        "-p", f"127.0.0.1:{port}:8080",
        "-v", f"{settings.parent}:/etc/searxng",
        IMAGE,
    ]
    try:
        result = _run(argv)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"ok": False, "detail": f"docker run failed: {exc}"}
    if result.returncode != 0:
        detail = ((result.stderr or "") + (result.stdout or "")).strip()[:400]
        return {"ok": False, "detail": detail or "docker run failed"}
    return {"ok": True, "detail": f"started on 127.0.0.1:{port}",
            "base_url": base_url(port)}


def stop() -> dict:
    docker = _docker()
    if not docker:
        return {"ok": False, "detail": "docker is not installed"}
    try:
        result = _run([docker, "rm", "-f", CONTAINER_NAME], timeout=30)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"ok": False, "detail": str(exc)}
    return {"ok": result.returncode == 0,
            "detail": "removed" if result.returncode == 0
                      else (result.stderr or "").strip()[:400]}


def _probe_json(url: str, timeout: int):
    request = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return json.loads(response.read(65536).decode("utf-8", errors="replace"))


def wait_ready(attempts: int = 20, delay: float = 1.5,
               port: int | None = None) -> dict:
    """Poll the JSON API until it answers.

    A ValueError means the endpoint served something that is not JSON — i.e.
    `json` is missing from search.formats. That is the single most common
    misconfiguration, so it gets its own message instead of a generic timeout
    the user cannot act on.
    """
    probe = f"{base_url(port)}agent8088-readiness-check&format=json"
    last = ""
    for _ in range(max(1, attempts)):
        try:
            _probe_json(probe, timeout=5)
            return {"ok": True, "detail": "JSON API responding"}
        except ValueError:
            return {"ok": False,
                    "detail": "instance is up but did not return JSON — add `json` "
                              "to search.formats in settings.yml"}
        except Exception as exc:  # noqa: BLE001 — transport variety during boot
            last = str(exc)
        time.sleep(delay)
    return {"ok": False,
            "detail": f"instance did not become ready ({last or 'no response'})"}
