import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarClock, Loader2, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { apiFetch } from '@/lib/api'
import { ErrorCard } from '@/components/ErrorCard'

type Schedule = { schedule: string; task: string; entry?: string }
type ScheduleResponse = { entries: Schedule[]; detail: string; error?: string }
async function list(): Promise<ScheduleResponse> { return apiFetch<ScheduleResponse>('/api/schedules', { action: 'load the schedule list' }) }
async function change(body: Record<string, string | boolean>) { return apiFetch<{ error?: string; confirmation_required?: boolean; message?: string }>('/api/schedules', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body), action: 'change that schedule' }) }

export default function SchedulesPage() {
  const queryClient = useQueryClient(); const [schedule, setSchedule] = useState('0 9 * * *'); const [task, setTask] = useState('')
  const schedules = useQuery({ queryKey: ['schedules'], queryFn: list })
  const mutation = useMutation({ mutationFn: async (body: Record<string, string>) => { const first = await change(body); if (first.confirmation_required && window.confirm(first.message || 'Continue?')) { const second = await change({ ...body, confirmed: true }); if (second.error) throw new Error(second.error); return second } if (first.error) throw new Error(first.error); return first }, onSuccess: () => { setTask(''); queryClient.invalidateQueries({ queryKey: ['schedules'] }) } })
  return <div className="mx-auto max-w-4xl space-y-5 p-4 sm:p-6"><div className="flex items-center gap-2.5"><CalendarClock className="h-5 w-5 text-brand-cyan" /><div><h1 className="text-lg font-semibold text-zinc-100">Schedules</h1><p className="text-xs text-zinc-500">Unattended tasks retain the engine’s cron and permission validation.</p></div></div><form onSubmit={(event) => { event.preventDefault(); mutation.mutate({ action: 'add', schedule, task }) }} className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-4"><div className="grid gap-2 sm:grid-cols-[180px_1fr_auto]"><input value={schedule} onChange={(event) => setSchedule(event.target.value)} aria-label="Cron schedule" className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 font-mono text-sm text-zinc-100" /><input value={task} onChange={(event) => setTask(event.target.value)} placeholder="Task to run…" aria-label="Scheduled task" className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 text-sm text-zinc-100" /><button disabled={!task.trim() || mutation.isPending} className="inline-flex items-center justify-center gap-1.5 rounded-lg bg-brand-primary px-3 py-2 text-sm text-white"><Plus className="h-4 w-4" />Add</button></div></form>{mutation.error && <ErrorCard error={mutation.error} action="change that schedule" onRetry={() => mutation.reset()} />}
{schedules.isError && <ErrorCard error={schedules.error} action="load the schedule list" onRetry={() => void schedules.refetch()} />}<section className="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900/50"><div className="border-b border-zinc-800 px-4 py-3 text-sm font-semibold text-zinc-200">Managed schedules</div>{schedules.isError ? <p className="p-8 text-center text-sm text-zinc-500">Could not load the schedule list — see the message above.</p> : schedules.isLoading ? <Loader2 className="m-8 h-5 w-5 animate-spin text-brand-cyan" /> : schedules.data?.entries.length ? schedules.data.entries.map((item, index) => <div key={`${item.schedule}-${item.task}-${index}`} className="flex items-center gap-3 border-b border-zinc-800 p-4 last:border-0"><span className="font-mono text-xs text-brand-cyan">{item.schedule || 'platform entry'}</span><span className="min-w-0 flex-1 truncate text-sm text-zinc-300">{item.task || item.entry}</span><button onClick={() => mutation.mutate({ action: 'remove', task: item.task })} className="text-red-400 hover:text-red-300" aria-label="Remove schedule"><Trash2 className="h-4 w-4" /></button></div>) : <p className="p-8 text-center text-sm text-zinc-500">{schedules.data?.detail || 'No scheduled tasks.'}</p>}</section></div>
}
